# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from local_dep/dep.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.4.0 with parameter "map_imports=google/:".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from google.rpc import status_pb
from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from google.rpc.status_pb import Status
    from protobuf import DescFile


_DepFields: TypeAlias = Literal["value", "status"]

class Dep(Message[_DepFields]):
    """
    ```proto
    message local_dep.Dep
    ```

    Attributes:
        value:
            ```proto
            string value = 1;
            ```
        status:
            ```proto
            optional google.rpc.Status status = 2;
            ```
    """

    __slots__ = ("value", "status")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            value: str = "",
            status: Status | None = None,
        ) -> None:
            pass

        value: str
        status: Status | None


_DESC = file_desc(
    b'\n\x13local_dep/dep.proto\x12\tlocal_dep\x1a\x17google/rpc/status.proto"G\n\x03Dep\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12*\n\x06status\x18\x02 \x01(\x0b2\x12.google.rpc.StatusR\x06statusb\x06proto3',
    [
        status_pb.desc(),
    ],
    {
        "Dep": Dep,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `local_dep/dep.proto`."""
    return _DESC
