# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from google/protobuf/c_sharp_features.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "no_fmt_off,init_files=false".
# ruff: noqa: PGH004
# ruff: noqa

from __future__ import annotations

from typing import Final, Literal, TYPE_CHECKING, TypeAlias

from protobuf import Extension, Message
from protobuf._codegen import file_desc

from . import descriptor_pb
from .descriptor_pb import FeatureSet

if TYPE_CHECKING:
    from protobuf import DescFile


_CSharpFeaturesFields: TypeAlias = Literal["nullable_reference_types"]


class CSharpFeatures(Message[_CSharpFeaturesFields]):
    """
    ```proto
    message pb.CSharpFeatures
    ```

    Attributes:
        nullable_reference_types:
            Whether the generated files should have nullable reference type annotations.
            When enabled, the generated C# code includes `#nullable enable annotations`
            and annotates message-typed properties and certain parameters with `?`.

            ```proto
            optional bool nullable_reference_types = 1;
            ```
    """

    __slots__ = ("nullable_reference_types",)

    if TYPE_CHECKING:

        def __init__(self, *, nullable_reference_types: bool | None = None) -> None: ...

        nullable_reference_types: bool


ext_csharp: Final[Extension[FeatureSet, CSharpFeatures]] = Extension()
"""
```proto
extend google.protobuf.FeatureSet { optional pb.CSharpFeatures csharp = 1004 [json_name = "[pb.csharp]"] }
```
"""


_DESC = file_desc(
    b'\n&google/protobuf/c_sharp_features.proto\x12\x02pb\x1a google/protobuf/descriptor.proto"k\n\x0eCSharpFeatures\x12Y\n\x18nullable_reference_types\x18\x01 \x01(\x08R\x16nullableReferenceTypesB\x1f\x88\x01\x01\x98\x01\x04\x98\x01\x03\x98\x01\x01\xa2\x01\n\x18\x84\x07\x12\x05false\xb2\x01\x03\x08\xea\x07:H\n\x06csharp\x18\xec\x07 \x01(\x0b2\x12.pb.CSharpFeatures\x12\x1b.google.protobuf.FeatureSetR\x06csharpB9B\x18CSharpFeaturesOuterClassP\x01\xaa\x02\x1aGoogle.Protobuf.Reflection',
    [descriptor_pb.desc()],
    {"CSharpFeatures": CSharpFeatures, "csharp": ext_csharp},
)


def desc() -> DescFile:
    """Returns the descriptor for the file `google/protobuf/c_sharp_features.proto`."""
    return _DESC
