# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from google/protobuf/cpp_file_options.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "no_fmt_off,init_files=false".
# ruff: noqa: PGH004
# ruff: noqa

from __future__ import annotations

from typing import Final, Literal, TYPE_CHECKING, TypeAlias

from protobuf import Extension, Message
from protobuf._codegen import file_desc

from . import descriptor_pb
from .descriptor_pb import FileOptions

if TYPE_CHECKING:
    from protobuf import DescFile


_CppFileOptionsFields: TypeAlias = Literal["namespace"]


class CppFileOptions(Message[_CppFileOptionsFields]):
    """
    ```proto
    message pb.file.CppFileOptions
    ```

    Attributes:
        namespace:
            Use this option to change the namespace of cpp generated classes. When this
            option is not set, the package name will be used for determining the cpp
            namespace.

            ```proto
            optional string namespace = 1;
            ```
    """

    __slots__ = ("namespace",)

    if TYPE_CHECKING:

        def __init__(self, *, namespace: str | None = None) -> None: ...

        namespace: str


ext_cpp: Final[Extension[FileOptions, CppFileOptions]] = Extension()
"""
```proto
extend google.protobuf.FileOptions { optional pb.file.CppFileOptions cpp = 990 [json_name = "[pb.file.cpp]"] }
```
"""


_DESC = file_desc(
    b'\n&google/protobuf/cpp_file_options.proto\x12\x07pb.file\x1a google/protobuf/descriptor.proto"0\n\x0eCppFileOptions\x12\x1c\n\tnamespace\x18\x01 \x01(\tR\tnamespaceX\x01:P\n\x03cpp\x18\xde\x07 \x01(\x0b2\x17.pb.file.CppFileOptions\x12\x1c.google.protobuf.FileOptionsR\x03cppB\x06\xb2\x01\x03\x08\xea\x07b\x08editionsp\xe9\x07',
    [descriptor_pb.desc()],
    {"CppFileOptions": CppFileOptions, "cpp": ext_cpp},
)


def desc() -> DescFile:
    """Returns the descriptor for the file `google/protobuf/cpp_file_options.proto`."""
    return _DESC
