# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from google/protobuf/json_enumvalue_options.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.6.0 with parameter "no_fmt_off,init_files=false".
# ruff: noqa: PGH004
# ruff: noqa
# pyright: reportDeprecated=false
# ty: ignore[unused-ignore-comment]
# ty: ignore[deprecated, unused-ignore-comment]

from __future__ import annotations

from typing import Final, Literal, TYPE_CHECKING, TypeAlias

from protobuf import Extension, Message
from protobuf._codegen import file_desc

from . import descriptor_pb
from .descriptor_pb import EnumValueOptions

if TYPE_CHECKING:
    from protobuf import DescFile


_JsonEnumValueOptionsFields: TypeAlias = Literal["string"]


class JsonEnumValueOptions(Message[_JsonEnumValueOptionsFields]):
    """
    ```proto
    message pb.enumvalue.JsonEnumValueOptions
    ```

    Attributes:
        string:
            Allows user to specify a custom string to use when serializing an enum
            value to JSON.

            Sample usage:
            enum Foo {
              ...
              FOO_BAR = 42 [(pb.enumvalue.json).string = "my_custom_name"];
            }

            ```proto
            optional string string = 1;
            ```
    """

    __slots__ = ("string",)

    if TYPE_CHECKING:

        def __init__(self, *, string: str | None = None) -> None:
            pass

        string: str


ext_json: Final[Extension[EnumValueOptions, JsonEnumValueOptions]] = Extension()
"""
```proto
extend google.protobuf.EnumValueOptions { optional pb.enumvalue.JsonEnumValueOptions json = 998 [json_name = "[pb.enumvalue.json]"] }
```
"""


_DESC = file_desc(
    b'\n,google/protobuf/json_enumvalue_options.proto\x12\x0cpb.enumvalue\x1a google/protobuf/descriptor.proto"0\n\x14JsonEnumValueOptions\x12\x16\n\x06string\x18\x01 \x01(\tR\x06stringX\x01:b\n\x04json\x18\xe6\x07 \x01(\x0b2".pb.enumvalue.JsonEnumValueOptions\x12!.google.protobuf.EnumValueOptionsR\x04jsonB\x06\xb2\x01\x03\x08\xea\x07B\x1a\n\x18com.google.protobuf.utilb\x08editionsp\xe9\x07',
    [descriptor_pb.desc()],
    {"JsonEnumValueOptions": JsonEnumValueOptions, "json": ext_json},
)


def desc() -> DescFile:
    """Returns the descriptor for the file `google/protobuf/json_enumvalue_options.proto`."""
    return _DESC
