# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from __future__ import annotations

from textwrap import dedent
from typing import TYPE_CHECKING

from protoc_gen_py import _generate, _Options

from tests.conftest import Plugin

if TYPE_CHECKING:
    from tests.conftest import Protoc


# We test protoc-gen-py within the protobuf plugin's unit test to reuse test harnesses.
# In the future, if we provide a public protoc plugin testing API, we can use it to
# move these to protoc-gen-py itself.


class TestOptions:
    def test_init_files_default(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"foo/bar/baz.proto": 'syntax = "proto3"; package foo.bar;'},
        )
        assert resp.error == ""
        file_names = {f.name for f in resp.file}
        assert "foo/bar/baz_pb.py" in file_names
        assert "__init__.py" in file_names
        assert "foo/__init__.py" in file_names
        assert "foo/bar/__init__.py" in file_names

    def test_init_files_off_suppresses(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"foo/bar/baz.proto": 'syntax = "proto3"; package foo.bar;'},
            parameter="init_files=false",
        )
        assert resp.error == ""
        file_names = {f.name for f in resp.file}
        assert "foo/bar/baz_pb.py" in file_names
        assert "__init__.py" not in file_names
        assert "foo/__init__.py" not in file_names
        assert "foo/bar/__init__.py" not in file_names

    def test_escaped_module_self_reference(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {"a-b.proto": 'syntax = "proto3"; package foo; message Foo { Foo f = 1; }'},
            parameter="escape_module_with_hash",
        )
        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        assert (
            files["a_b_d44362d6_pb.py"]
            == dedent(
                r'''
            # Generated from a-b.proto. DO NOT EDIT.
            # Generated by protoc-gen-test v1.0.0 with parameter "escape_module_with_hash".
            # ruff: noqa: PGH004
            # ruff: noqa
            # fmt: off

            from __future__ import annotations

            from typing import Literal, TYPE_CHECKING, TypeAlias

            from protobuf import Message
            from protobuf._codegen import file_desc

            if TYPE_CHECKING:
                from protobuf import DescFile


            _FooFields: TypeAlias = Literal["f"]

            class Foo(Message[_FooFields]):
                """
                ```proto
                message foo.Foo
                ```

                Attributes:
                    f:
                        ```proto
                        optional foo.Foo f = 1;
                        ```
                """

                __slots__ = ("f",)

                if TYPE_CHECKING:

                    def __init__(
                        self,
                        *,
                        f: Foo | None = None,
                    ) -> None: ...

                    f: Foo | None


            _DESC = file_desc(
                b'\n\ta-b.proto\x12\x03foo"\x1d\n\x03Foo\x12\x16\n\x01f\x18\x01 \x01(\x0b2\x08.foo.FooR\x01fb\x06proto3',
                [],
                {
                    "Foo": Foo,
                },
            )


            def desc() -> DescFile:
                """Returns the descriptor for the file `a-b.proto`."""
                return _DESC
            '''
            ).lstrip()
        )

    def test_external_dependency(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {
                "app/main.proto": """
                syntax = "proto3";
                package app;
                import "buf/validate/validate.proto";
                message Main {
                    buf.validate.Rule rule = 1;
                }
                """,
                "buf/validate/validate.proto": """
                syntax = "proto3";
                package buf.validate;
                message Rule {}
                """,
            },
            files_to_generate=["app/main.proto"],
            parameter="map_imports=buf/validate/:",
        )

        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        assert set(files) == {"__init__.py", "app/__init__.py", "app/main_pb.py"}
        main = files["app/main_pb.py"]
        assert "from buf.validate import validate_pb" in main
        assert "from buf.validate.validate_pb import Rule" in main
        assert "from ..buf.validate" not in main


class TestDeprecated:
    def test_deprecated_message_and_enum(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {
                "foo.proto": """
                syntax = "proto3";
                package foo;
                message Foo {
                    option deprecated = true;
                }
                enum Bar {
                    option deprecated = true;
                    BAR_UNSPECIFIED = 0;
                }
                """
            },
        )
        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        assert (
            files["foo_pb.py"]
            == dedent(
                r'''
            # Generated from foo.proto. DO NOT EDIT.
            # Generated by protoc-gen-test v1.0.0 with parameter "".
            # ruff: noqa: PGH004
            # ruff: noqa
            # pyright: reportDeprecated=false
            # ty: ignore[deprecated]
            # fmt: off

            from __future__ import annotations

            from typing import NoReturn, TYPE_CHECKING, TypeAlias

            from protobuf import Enum, Message
            from protobuf._codegen import file_desc
            from typing_extensions import deprecated

            if TYPE_CHECKING:
                from protobuf import DescFile


            _deprecated = deprecated

            _FooFields: TypeAlias = NoReturn

            @_deprecated("foo.Foo is deprecated.", category=None)
            class Foo(Message[_FooFields]):
                """
                ```proto
                message foo.Foo [deprecated = true]
                ```
                """

                __slots__ = ()

                if TYPE_CHECKING:

                    def __init__(
                        self,
                    ) -> None: ...

            @_deprecated("foo.Bar is deprecated.", category=None)
            class Bar(Enum):
                """
                ```proto
                enum foo.Bar [deprecated = true]
                ```

                Attributes:
                    UNSPECIFIED:
                        ```proto
                        BAR_UNSPECIFIED = 0
                        ```
                """

                UNSPECIFIED = 0


            _DESC = file_desc(
                b'\n\tfoo.proto\x12\x03foo"\t\n\x03Foo:\x02\x18\x01*\x1e\n\x03Bar\x12\x13\n\x0fBAR_UNSPECIFIED\x10\x00\x1a\x02\x18\x01b\x06proto3',
                [],
                {
                    "Foo": Foo,
                    "Bar": Bar,
                },
            )


            def desc() -> DescFile:
                """Returns the descriptor for the file `foo.proto`."""
                return _DESC
            '''
            ).lstrip()
        )

    def test_reference_to_deprecated_message(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {
                "a.proto": """
                syntax = "proto3";
                package a;
                import "b.proto";
                message A {
                    b.B b = 1;
                }
                """,
                "b.proto": """
                syntax = "proto3";
                package b;
                message B {
                    option deprecated = true;
                }
                """,
                "c.proto": """
                syntax = "proto3";
                package c;
                message C {
                    int32 c = 1 [deprecated = true];
                }
                """,
            },
            files_to_generate=["a.proto", "c.proto"],
        )
        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        # Only declarations are marked, not references to them.
        assert "_deprecated" not in files["a_pb.py"]
        assert "int32 c = 1 [deprecated = true];" in files["c_pb.py"]
        assert "def c(self) -> int: ..." in files["c_pb.py"]
        # Deprecation is only suppressed when a deprecated type is referenced.
        assert "# ty: ignore[deprecated]\n" in files["a_pb.py"]
        assert "# ty: ignore[deprecated]\n" not in files["c_pb.py"]

    def test_deprecated_extension_and_enum_value(self, protoc: Protoc) -> None:
        resp = protoc.run_plugin(
            Plugin(_generate, options=_Options),
            {
                "a.proto": """
                syntax = "proto2";
                package a;
                message A {
                    extensions 1 to 10;
                    extend A {
                        optional int32 nested = 1 [deprecated = true];
                    }
                }
                extend A {
                    optional int32 top = 2 [deprecated = true];
                }
                enum E {
                    E_UNSPECIFIED = 0;
                    E_OLD = 1 [deprecated = true];
                }
                message D {
                    option deprecated = true;
                    extensions 1 to 10;
                }
                extend D {
                    optional int32 d_ext = 1;
                }
                """
            },
        )
        assert resp.error == ""
        files = {f.name: f.content for f in resp.file}
        a = files["a_pb.py"]
        # Extensions can't be marked.
        assert "class A(Message[_AFields]):\n" in a
        assert "def ext_" not in a
        assert "def OLD(cls) -> E: ..." in a
        assert "ext_d_ext: Final[Extension[D, int]] = Extension()\n" in a
