# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from local_import/importer.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.4.0 with parameter "map_imports=google/:".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

from ..local_dep import dep_pb

if TYPE_CHECKING:
    from protobuf import DescFile

    from ..local_dep.dep_pb import Dep


_ImporterFields: TypeAlias = Literal["dep"]

class Importer(Message[_ImporterFields]):
    """
    ```proto
    message local_import.Importer
    ```

    Attributes:
        dep:
            ```proto
            optional local_dep.Dep dep = 1;
            ```
    """

    __slots__ = ("dep",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            dep: Dep | None = None,
        ) -> None:
            pass

        dep: Dep | None


_DESC = file_desc(
    b'\n\x1blocal_import/importer.proto\x12\x0clocal_import\x1a\x13local_dep/dep.proto",\n\x08Importer\x12 \n\x03dep\x18\x01 \x01(\x0b2\x0e.local_dep.DepR\x03depb\x06proto3',
    [
        dep_pb.desc(),
    ],
    {
        "Importer": Importer,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `local_import/importer.proto`."""
    return _DESC
