name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "src/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"
  pull_request:
    paths:
      - "docs/**"
      - zensical.toml
      - ".github/workflows/docs.yaml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - run: uv run --group docs --no-dev zensical build --clean --strict

      - name: deploy preview
        if: github.event_name == 'pull_request' && !github.event.repository.fork
        run: |
          curl -sS --fail-with-body -X POST "https://api.vercel.com/v13/deployments?teamId=${{ secrets.VERCEL_ORG_ID }}&forceNew=1" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$(cat <<EOF
          {
            "project": "${{ secrets.VERCEL_PROJECT_ID }}",
            "name": "protobuf-py",
            "gitSource": {
              "type": "github",
              "org": "${{ github.repository_owner }}",
              "repo": "${{ github.event.repository.name }}",
              "ref":  "${{ github.head_ref }}",
              "sha": "${{ github.event.pull_request.head.sha }}",
              "prId": ${{ github.event.pull_request.number }}
            }
          }
          EOF
          )"
